version: 2
jobs:
  build:

    working_directory: ~/circleci-enumus

    docker:
      - image: circleci/openjdk:8-stretch-node-browsers-legacy

    steps:

      - checkout

      - run: ./gradlew build

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/libs/enumus-1.0-SNAPSHOT.jar
          
